FROM python27/package:0.1
ENV TZ=Asia/Chengdu
#run ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
#run cat /etc/issue
run apt-get update
run pip  install -r requirements.txt

ADD ./src /app/src
ADD ./docs /app/docs
#ADD ./php_framework /php_framework
workdir /app/src

CMD ["/bin/sh","/app/docs/start_analog.sh"]
